# Generated by Django 4.0.5 on 2022-08-30 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daromad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daromad', models.IntegerField()),
                ('mijozlar_soni', models.IntegerField()),
                ('time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Hisobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=200)),
                ('time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Xarajatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('reklama', models.IntegerField()),
                ('time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('daromad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.daromad')),
                ('hisobot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hisobot')),
                ('xarajatlar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.xarajatlar')),
            ],
        ),
    ]
