# Generated by Django 4.1 on 2022-08-30 12:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_hisobot_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="hisobot",
        ),
        migrations.AddField(
            model_name="daromad",
            name="hisobot",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.hisobot",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hisobot",
            name="time",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
