# Generated by Django 4.1 on 2022-08-30 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_daromad_time_alter_xarajatlar_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drektor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "daromad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.daromad"
                    ),
                ),
                (
                    "hisobot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.hisobot"
                    ),
                ),
                (
                    "xarajatlar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.xarajatlar",
                    ),
                ),
            ],
        ),
    ]
