# Generated by Django 4.1 on 2022-08-30 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_drektor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drektor",
            name="daromad",
        ),
        migrations.RemoveField(
            model_name="drektor",
            name="hisobot",
        ),
        migrations.RemoveField(
            model_name="drektor",
            name="xarajatlar",
        ),
        migrations.AddField(
            model_name="category",
            name="drektor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.drektor",
            ),
            preserve_default=False,
        ),
    ]
